apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: default
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgAdFETfLt5fK0n0LL28m9kfHwbu1MXm2G3EVRT1q737TMZ6NwvHg9Q2OssYV1r4rCB8iUtfVFQ6UWrUyYINYBn8t7YoTqrcZN20FbF36BdMSZJCT8qHhPrysHrSf9GcSmx10gIyIlEqYVgj/gK4WYKdLjJeRfolGefe4nmlxjPrvBmGgQlnmcGTH+o0TF+ePH301V6oxKiXQa0JmpfQeJFApAtUFMGybMWfVWPRoxkT+8/XRs4x9iVVwi130CnIXR9k7DWs/eKYgeGyyt3TYaRHzN5hcxl2dr1bI/ZpzwkbHdYYMuWnb9YOoeajMI/8YmBl334lsBeh8K0UJ+z5vzUbVK4pG0zFG0DgaEkiWQPZ/dQDh4cICtjkqXSuowOZWwT44NQ7IECjA0mC6WGMFlrz4WEEdf5jKfsOpC5RW0mxNT8dSUIPascNdpA0WnYIkgMNXpRPaJhg75tgEwBF9LEXfWY7hE5Mch0gxg2wuix8EvyLYSP28CG46iaU8CQliRA6EHQsvU+mIyPOhrRZNksLdaEh7FAlhILYXy8jmtNkpeekZef9u1/jsbnRaE8WP0UOtcU8HP84zdWl+EgN3xGvWQV0pfE0zBDIx6CWqY9y8Rp7zVq5bWj/OupC1Mp/W12dE68vd7C9MtFF1Xx+Ny+5cW8M7SlPp+KxpLyVf9dN5vTH3D8WL1Ly1FeoYq+pSAuVdug=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: default
    type: Opaque

