apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080       # Port exposed by the service
      targetPort: 8080 # Port on the Jenkins container
      nodePort: 30007  # Static NodePort (accessible on the node's IP at this port)
  type: NodePort        # Service type

