apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: omarz1/finalproject:backend4
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              value: "5000" 
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DB
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MYSQL_DB
          volumeMounts:
            - name: backend-persistent-storage
              mountPath: /data
      imagePullSecrets:
        - name: image-pull-auth
      volumes:
        - name: backend-persistent-storage
          persistentVolumeClaim:
            claimName: backend-pvc
